
  name: fibonaccis
  version: '0.4'
  summary: program that makes the sequence of fibonacci
  description: |
    This is my-snap's description. You have a paragraph or two to tell the
    most important story about your snap. Keep it under 100 words though,
    we live in tweetspace and your description wants to look good in the snap
    store.

  grade: devel

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
